### ISSUE TITLE
Build status is broken

### ISSUE THREAD

**Issue by jim-bo** [dfci/cidc-taskmanager#39]
@mtmcduffie Suggest getting these badges working, successful open-source projects have these automated checks working and visible as a sign of the projects health. Seeing a broken link is bad. Other option is to remove the badge [not my preference].

![image](https://user-images.githubusercontent.com/317043/48778278-bfb57f00-eca2-11e8-8c10-ed241ec67949.png)

**Comment by lemccarthy** [comment]
@jim-bo the plugin that did this for jenkins is abandoned and no longer working with newer versions of jenkins. I will remove it, and unfotunately I haven't found any way to replace it.
